### ISSUE TITLE
hangul-josa: New API

### ISSUE THREAD

**Issue by simnalamburt** [simnalamburt/npm#1]
```js
import josa from 'hangul-josa'

const player = '지현'
const skill = '구르기'

console.log(josa`${player}는 ${skill}을 사용했다!`)
// 지현은 구르기를 사용했다!
```

###### Reference:
- https://twitter.com/saschanaz/status/1297443013866782722

**Comment by simnalamburt** [comment]
@saschanaz 근데 의도치않게 찾아바꾸기 하는 경우가 생길까봐 조금 우려되긴 하네요. 그런 경우는 없을라나요?

**Comment by saschanaz** [comment]
`${3}가 백신` 같은 경우는 의도치 않은 오류가 생길 수도 있겠네요.

**Comment by simnalamburt** [comment]
그냥 명시적인 API로 존치하는게 어떨까 싶은데 어떻게 생각하시나용 👀

사실 은는이가 지정을 문자열로 안하고 아래와 같이 Symbol로 한다음 변수로 넘기게 한것도, 의도하지 않았는데 변환되는 경우를 막기 위험이었거든용.

https://github.com/simnalamburt/npm/blob/fb27ea556c8fc0255d07873c9c193a10caab590f/packages/hangul-josa/src/index.ts#L3-L7

**Comment by saschanaz** [comment]
긴글에 일괄 적용하는 게 아니라 인라인으로 쓰는 함수니 이런 레어한 예시는 `	${3}${"가"}` 정도로 적당히 회피 가능하지 싶어요

**Comment by simnalamburt** [comment]
새 API를 구현해보고 좀 써보고 판단을 해볼게용

**Comment by simnalamburt** [comment]
이렇게 하니까 으로부터/로부터 으로도/로도 처리가 복잡해지네요 전에는 걍 `${으로}부터` 이렇게하면 다 처리가 됐는데 🤔

**Comment by simnalamburt** [comment]
이렇게 하려니 string match도 복잡해지고, 이로인해 불가피하게 코드사이즈도 커져서 몬가 hangul-josa 취지엔 안맞는것같아용. 새로운 조사 라이브러리에서는 이런 접근을 쓸 수 있을것같지만 hangul-josa 취지엔 안맞는것같아 close합니다.
